/**
 * The test class TestGraph.  Generated by BlueJ.
 *
 * Copyright BlueJ authors
 * Copyright 2011 Jan Minar <rdancer@rdancer.org>  Licensed under the GNU GPL v2.
 *
 * @author BlueJ authors
 * @author Jan Minar <rdancer@rdancer.org> 
 */

import java.io.*;


public class TestGraph extends junit.framework.TestCase
{
    /**
     * Default constructor for test class TestGraph
     */
    public TestGraph()
    {
    }

    /**
     * Sets up the test fixture.
     *
     * Called before every test case method.
     */
    protected void setUp()
    {
    }

    /**
     * Tears down the test fixture.
     *
     * Called after every test case method.
     */
    protected void tearDown()
    {
    }

    public void testNewGraphFromString()
            throws Exception
    {
        int vertexCount = 6;
        int edgeCount = 8;
        Graph myGraph = new Graph("" + vertexCount + ", " + edgeCount + ", (1, 2, 5.7), (1, 5, 2.4), (1, 3, 3.7), (2, 3, 9.5), (2, 5, 1.9), (3, 4, 1.2), (4, 5, 4.0), (4, 6, 3.7)");
        
        assert(myGraph.vertexCount == vertexCount);
        assert(myGraph.edgeCount == edgeCount);
        
        System.out.println(myGraph);
    }

    public void testNewGraphFromFile()
            throws Exception
    {
        int vertexCount = 6;
        int edgeCount = 8;
        Graph myGraph = new Graph(new File("sample_input"));
        Graph myGraph2 = new Graph("" + vertexCount + ", " + edgeCount + ", (1, 2, 5.7), (1, 5, 2.4), (1, 3, 3.7), (2, 3, 9.5), (2, 5, 1.9), (3, 4, 1.2), (4, 5, 4.0), (4, 6, 3.7)");
                
        assert(myGraph.vertexCount == vertexCount);
        assert(myGraph.edgeCount == edgeCount);
        
        assert(myGraph.toString().equals(myGraph2.toString()));
    }
    
    
}

